steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA', '.'] # Replace twitter-bot-image
images:
- 'gcr.io/$PROJECT_ID/gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA'
logsBucket: gs://twitter_github_123
