steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/twitterbotimage:${COMMIT_SHA:-latest}', '.']
images:
  - 'gcr.io/$PROJECT_ID/twitterbotimage:${COMMIT_SHA:-latest}'

