services:
  - type: web
    name: cryptosocialbot  
    env: python
    region: ohio  
    plan: free  
    branch: main  
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /