name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: nth-infusion-449206-d6

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/nth-infusion-449206-d6/your-image-name

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-service-name \
            --image=gcr.io/nth-infusion-449206-d6/your-image-name \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated

